- package.json
- src/Tasks/Suggest.js
currently, when `useMapBounds` is true, for suggest requests, we append `location` and `distance` parameters dynamically but fail to set `searchExtent`.  this has the undesired effect of ranking results based on their proximity to map center, but failing to omit results outside the relevant bounding box.
STR:
1. load [this](http://esri.github.io/esri-leaflet/examples/geocoding-control.html) sample and zoom in on downtown portland (past level 12, which sets useMapBounds automatically).
2. search for 'voodoo' and notice that the Portland match is returned first, but results in other locations are included in the result as well.
proposed fix is included.  additional, tangentially related discussion can be found in #38
> add 'searchExtent' to suggest requests dynamically

- README.md
- debug/sample.html
- src/Controls/Geosearch.js
- src/Providers/GeocodeService.js
- src/Services/Geocoding.js
- src/Tasks/Geocode.js
closes #64
* fixed `FeatureLayer` provider instantiation syntax in 'debug/sample.html' (unrelated)
* a few copyedits in doc
* added a quick metadata request during initialization for the `Geocoding` service to determine whether or not 'Suggest' is a supported capability.
* added logic to the provider to hook things up
> added support for custom 10.3 geocoding services that support 'suggest'

- .travis.yml
- CHANGELOG.md
- debug/sample.html
- index.html
- package.json
- src/Providers/FeatureLayer.js
- src/Providers/MapService.js
closes #74 
had to ditch the GIS day feature service because it doesn't look like its up anymore.
in the middle of refactoring i noticed that developers have to `new` up their 'Provider' objects because we don't do 
```js
EsriLeafletGeocoding.Controls.Geosearch.Providers.featureLayer = function(options){
return new EsriLeafletGeocoding.Controls.Geosearch.Providers.FeatureLayer;
};
```
is that an intentional deviation?
> 1.0.0 refactor

- src/Services/Geocoding.js
The latest update to the plugin breaks because the response.capabilities is undefined on an ArcGIS Server 10.2 custom geocode service. This appears to fix the issue.
I've created a [gist](https://gist.github.com/npeihl/f37c81e311158cccbb32) showing how the debug/sample.html would look with our custom geocode service. I didn't include my changes to debug/sample.html in the commit.
> Fixes response.capabilities undefined error when using custom geocoder without ArcGIS Online Geoocoder.

- CHANGELOG.md
- README.md
- spec/Tasks/ReverseGeocodeSpec.js
- src/Tasks/ReverseGeocode.js
resolves #105
when i looked at the code i realized we weren't setting [`langCode`](https://developers.arcgis.com/rest/geocode/api-reference/geocoding-reverse-geocode.htm#ESRI_SECTION1_ABD1AD449DF54FFEB9527A606341714C) correctly either so i fixed that, updated the relevant test and got info into the doc.
> fix language input and add returnIntersection

- README.md
- spec/Controls/GeosearchSpec.js
- src/Controls/Geosearch.js
As stated.  Relates to #113.  
I couldn't figure out how to capture the request URL from the request XMLHTMLrequest object for the tests.  Does anyone have any ideas about the best approach?
> Add a searchBounds attribute to geocoder

- CHANGELOG.md
- spec/Controls/GeosearchSpec.js
- spec/Tasks/GeocodeSpec.js
- src/Controls/Geosearch.js
can't believe no one else reported this.
STR: 
1. launch the geosearch [sample](http://esri.github.io/esri-leaflet/examples/geocoding-control.html)
2. type, `texas` and accept the first match.
3. the map zooms in to street level even though the geocoding result includes [an extent](http://geocode.arcgis.com/arcgis/rest/services/World/GeocodeServer/find?outSr=4326&forStorage=false&outFields=*&maxLocations=20&text=Texas%2C%20United%20States&magicKey=GST7YMc0AM9UOsE9HhFtGTyVGST7YMc0AM9UOsE9DbTVHgA9HhB0Zcp0OhNtGMytaikZU5NJU5kHUoc4Hhp0OSTaSsEqAZ43AP9zJikuGPAmIYxQGPT-CZc0YiD7DsKJCZyAOh5-Dn47Z5EGOhtvY1FF&bbox=%7B%22xmin%22%3A-99.2531704902649%2C%22ymin%22%3A31.249291241150125%2C%22xmax%22%3A-99.2480367422104%2C%22ymax%22%3A31.251584282844966%2C%22spatialReference%22%3A%7B%22wkid%22%3A4326%7D%7D&f …
> make sure geosearch control aggregates result extents correctly

- src/Services/Geocode.js
i reproed a user reported error in IE11 with geosearch and the stock World Geocoding Service provider.
since that browser doesn't support `String.includes()`, altered the check to use the logic below instead.
```js
if (string.indexOf('foo') > -1) 
// proceed
```
> use `indexOf` instead of `includes` for old ie

- package.json
- spec/Controls/GeosearchSpec.js
- spec/Tasks/GeocodeSpec.js
- src/Providers/ArcgisOnlineGeocoder.js
- src/Services/Geocode.js
- src/Tasks/Geocode.js
- src/Tasks/Suggest.js
i would expect setting `maxResults` to impact how many *suggestions* are returned, not geocoding matches. 
right now, even though 'L.esri.geosearch' passes along a `maxResults` parameter when ultimately calling the `find` operation of the World Geocoding Service, since a `magicKey` is included too, only one candidate is ever going to come back.
this code change has the desired effect of exposing a technique to augment the number of suggestions returned, but needs a little more testing to make sure all is well with the other providers.
> ensure 'maxResults' limits the number of suggestions too

- debug/sample.html
- package.json
- spec/Controls/GeosearchSpec.js
- src/Controls/Geosearch.js
- src/Providers/ArcgisOnlineGeocoder.js
resolves #132 by ensuring consistent usage of 'Powered by Esri' when the ArcGIS Online World Geocoding service is referenced.
this shouldn't be merged until we tag a new esri-leaflet release.
> display 'Powered by Esri

- src/Providers/FeatureLayer.js
resolves #135
```js
L.esri.Geocoding.featureLayerProvider({
label: 'States',
url: 'http://sampleserver6.arcgisonline.com/arcgis/rest/services/Census/MapServer/3',
searchFields: ['STATE_NAME'],
// only return a match if the searched state population exceeds 10 million
where: 'POP2007 > 10000000'
})
```
> expose option to filter the features in featureLayer that will return a match

- package.json
- src/Classes/GeosearchCore.js
- src/Controls/Geosearch.js
this change ensures that the UI is updated appropriately in situations where the last request for suggestions returns no matches.
resolves #141 
additional, unrelated changes:
* the control no longer invokes custom attribution, so the onRemove() method is no longer necessary.
* switched back from the UNIX pipe (|) operator to single ampersand for concurrent commands because only 'npm run css' was being called when a change was made to source.
> clear loading icon when no matches are returned

- spec/Providers/FeatureLayerSpec.js
- src/Providers/FeatureLayer.js
when more than one field is searched, the collection of OR seperated LIKE queries on individual layers should be wrapped `( )`
> ensure correct precedence in concatenated sql clauses

- src/Providers/MapService.js
When false, the contains parameter requires the search text to match
exactly, even being case-sensitive. Removing this parameter will allow
fuzzy searches to go through. For example, type "king" and press enter 
on the debug page to return Kings, King, Kingman, ... counties from 
the map service.
I'm bypassing the suggestions in this example because as a user I'd expect 
the search to work similarly to a Google search (pressing enter returns results). 
See the attached gif. 
ref: #148
> Remove contains parameter from mapserver provider

- package.json
addresses #131 
using [parallelshell](https://www.npmjs.com/package/parallelshell) to make this work cross-platform.
This works for me on Windows 7.
@jmfolds @jgravois can you please test on your platforms? Thanks!
> fixed `npm start` working on windows

- src/Controls/Geosearch.js
resolves #151
this change introduces a check to compare suggestion text with what is already present in the list.
if the new suggestion isn't unique, it won't be added, but rather the existing item's `magicKey` will be updated using the identifier of the second feature.  this ensures that *all* matching features will be available in the results.
although the change is being made in the geosearch control itself, the effect should be limited to `featureLayerProvider` and `mapServiceProvider`, because geocoding services typically only return address candidates with distinct text.
> ensure duplicate geosearch suggestions are passed in results, but not displayed

- src/Providers/FeatureLayer.js
resolves #161
i tested with the others as well and the issue was definitely peculiar to `featureLayerProvider`.
> clear objectIds from query after results are returned

- spec/Controls/GeosearchSpec.js
- src/Controls/Geosearch.js
resolves #165 
there's probably a clever*er* way to do this, but this change ensures that we pass through user supplied options to `geosearchCore` when the default provider is utilized.
> stop accidently blowing away user supplied options

- src/Controls/Geosearch.js
- src/esri-leaflet-geocoder.css
resolves #160 
* don't render suggestions when the service doesn't return any
* bump width of contracted and expanded control (to account for borders) on browsers that support touch (like Chrome [55](https://blog.chromium.org/2016/10/chrome-55-beta-input-handling.html))
i'm gonna chew on this a bit before i merge because i'd like to think we can preserve `box-shadow` in Chrome instead.
> tweak touchscreen widths slightly

- src/Controls/Geosearch.js
resolves #159 
added a quick check to ensure that we don't send requests to geocoding or feature services when enter is clicked and nothing has been typed.
i also improved the logic a bit so that a request *is* fired automatically when enter is clicked with focus on the input textbox and a single suggestion is being displayed.
> dont try and geocode empty strings

- src/Controls/Geosearch.js
- src/Providers/ArcgisOnlineGeocoder.js
- src/Providers/FeatureLayer.js
- src/Providers/GeocodeService.js
- src/Providers/MapService.js
fix for #186 (only tested on Chrome's mobile emulator)
also caught a bug in which formatted display text was incorrectly passed back to the service in feature searches and another bug that manifested when users click or tap on the `<small>` context text instead of the actual string so i fixed those too.
`ex: San Bernardino <small>Detailed Counties</small>`
> enable touch selection for results

- .travis.yml
we're getting invalid errors in travis (on #221 for example) - `The command "sh -e /etc/init.d/xvfb start" failed and exited with 127 during .` - this config change should fix that.
per [here](https://benlimmer.com/2019/01/14/travis-ci-xvfb/) and [here](https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-xvfb-to-run-tests-that-require-a-gui).
> fix travis testing

- package-lock.json
- src/Classes/GeosearchCore.js
- src/Controls/Geosearch.js
Resolves enhancement issue #217.
Changes include:
- Now provider suggestion results are housed within a new DOM element child container for each provider, in order to maintain the configured order of providers for suggested results.
- Clearing the parent `this._suggestions` is handled a little bit differently.  Instead of its `innerHTML` being set to `''`, each of the providers' child container is cleared out; again, this is to maintain the original configured order.
Some questions which might create more work for another PR(s):
1. I can't tell how the `clearSuggestions` method is being actively used. Is this a holdover from previous functionality? https://github.com/Esri/esri-leaflet-geocoder/blob/87c9b7ed5335cfba88631b757c41a1fbb3519493/src/Controls/Geosearch.js#L157  It is being called …
> 217-providers-suggest-order

- CHANGELOG.md
- spec/Controls/GeosearchSpec.js
- src/Controls/Geosearch.js
Resolves #225.  A legitimate case was missed during human testing of enhancement #217. 
- Now the geocoder control shouldn't fail when there are no optional `providers` passed in.
- Added some related tests but these could likely be improved upon.
I recommend publishing another release after this makes it in (v2.3.1?).  Should we deprecate v2.3.0 after all is said and done?
> 225-providers-check

- .gitignore
- CHANGELOG.md
- debug/sample-multiple.html
- src/Controls/Geosearch.js
- src/esri-leaflet-geocoder.css
resolves #224 
- Suggestions are now shown above the geocoder input element when using the constructor option `position: 'bottomleft'` or `position: 'bottomright'`.
- Added a new sample page (see `debug/sample-multiple.html`) for testing out the changes in this PR.
- Note that this conditional block of code dealing with the control being in either of the top corners still contains the original css calculations to display suggestions under the geocoder input element. https://github.com/Esri/esri-leaflet-geocoder/compare/224-bottom-position#diff-5763e4da84ffa56f56019ee1a0ff7aacR100
- But the next conditional block of code contains the primary new additions that enable the suggestions to be visible above the geocoder input element when it is in the bottom corners.
- Altered 2 other portions …
> 224-bottom-position

- CHANGELOG.md
- debug/sample.html
- spec/Providers/FeatureLayerSpec.js
- spec/Providers/MapServiceSpec.js
- src/Providers/FeatureLayer.js
- src/Providers/MapService.js
Resolves #250.
- Fixed incorrect query vs. find REST request for the MapService provider when there are more than 1 magic keys available. (See issue comments in #250.)
- Added source code comments for both MapService and FeatureLayer providers regarding usage of keys.
- Added tests for MapService and FeatureLayer providers when there are more than 1 keys available.
- Misc. formatting for debug sample.html.
> 250-multi-magic-keys-bug

- CHANGELOG.md
- spec/Controls/GeosearchSpec.js
- src/Tasks/Suggest.js
Alleviates different "/suggest" vs. "/findAddressCandidates" behavior when a `searchBounds` option is used, by removing the automatically applied `bounds.pad(0.5)` in the suggest `within` method.
Related to #273.
Try to search for "park bench cafe" as described in #273 in the JSBin example, and then try again in a local checkout of this PR with the code sample provided below.
<details>
<summary markdown="span">local demo sample</summary>
```html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>Geocoding control</title>
<meta name="viewport" content="initial-scale=1,maximum-scale=1,user-scalable=no" />
<link rel="stylesheet" href="../node_modules/leaflet/dist/leaflet.css" />
<script src="../node_modules/leaflet/dist/leaflet-src.js"></script>
<script …
```
> 273-remove-suggest-pad

- CHANGELOG.md
- spec/Tasks/GeocodeSpec.js
- src/Tasks/Geocode.js
> properly pass through api key

- spec/Tasks/ReverseGeocodeSpec.js
- src/Tasks/ReverseGeocode.js
properly pass through `token` and `apikey` for `.reverseGeocode()`.
similar to #278. That PR was fixing `geocode()` where this PR is for `reverseGeocode()`
fixes #294 and #282
> for reverseGeocode, pass through apikey and token

- src/esri-leaflet-geocoder.css
Based on [this issue](https://github.com/Esri/esri-leaflet-geocoder/issues/230) where Geocoder suggestions appear under other Leaflet controls, this PR resolves that by increasing the z-index of the control itself from `800` as defined by Leaflet, to `801`.
Working example [here](https://codepen.io/McGaber/pen/GRbVyXx)
NOTE: You will need to supply your own Esri API key in the Codepen.
> Increase z-index of geocoder-control element

- index.d.ts
- package.json
Description:
TypeScript types file 
Fix: #319 
@gavinr-maps 
Kindle please review the PR.
> feat: TypeScript types file [#319]

- package.json
> fix: Include CSS source files in published package
