Esri/esri-leaflet-geocoder

- README.md
- src/Controls/Geosearch.js
- src/Providers/FeatureLayer.js
> Map attribution option

- README.md
Updated README to false.
Bumped to beta.4.
Signed-off-by: benstoltz <stoltz.ben@me.com>
> Default value for expanded constructor option #70

- spec/Providers/FeatureLayerSpec.js
- src/Providers/FeatureLayer.js
Don't know if this is the right approach, hope someone can tell me..
> Case Sensitive option on Feature Layer

- CHANGELOG.md
- README.md
- debug/sample.html
fixed debug/sample.html and bumped CHANGELOG to reflect @rntdrts's bugfix
> update debug sample

- src/Controls/Geosearch.js
> new up empty bounds objects

- .travis.yml
- README.md
- index.html
- karma.conf.js
- package.json
- scripts/build.js
- spec/Controls/GeosearchSpec.js
- spec/Providers/ArcgisOnlineGeocoderSpec.js
- spec/Providers/FeatureLayerSpec.js
- spec/Providers/GeocodeServiceSpec.js
- spec/Providers/MapServiceSpec.js
- spec/Services/GeocodingSpec.js
- spec/Tasks/GeocodeSpec.js
- spec/Tasks/ReverseGeocodeSpec.js
- spec/Tasks/SuggestSpec.js
- src/Controls/Geosearch.js
- src/EsriLeafletGeocoding.js
- src/Providers/FeatureLayer.js
- src/Providers/GeocodeService.js
- src/Providers/MapService.js
was having some serious trouble running `semistandard` locally and saw the same errors up on travis so i'm bumping the version
cc/ @kneemer
> bump semistandard to 7.0.2 (and fix linting problems)

- CHANGELOG.md
- README.md
- bower.json
- package.json
- spec/Controls/GeosearchSpec.js
- src/Controls/Geosearch.js
- src/EsriLeafletGeocoding.js
resolves #94, #93
this bug snuck in during the ES6 refactor 17f4940794652bbd7cb601a3a80b0081ea121809
i also laid down the groundwork to tag `2.0.1` here.
> make sure to pass user provided options

- .gitignore
- package.json
porting solution from Esri/esri-leaflet#654
> add watchify/automatic rebuild

- package.json
- spec/Controls/GeosearchSpec.js
- src/Controls/Geosearch.js
> make sure geosearch control adds appropriate provider attribution to the map

- bower.json
- package.json
will merge myself if everyone is happy with Esri/esri-leaflet#699
> syncronize npm/bower version dependencies

- README.md
> link to API reference on esri leaflet website

- README.md
> minor example code fix

- debug/sample.html
- src/Providers/ArcgisOnlineGeocoder.js
> pass through maxSuggestions, even with magicKey

- src/Controls/Geosearch.js
> make world geocoding service the default provider

- .travis.yml
- package.json
resolves #131 
works with Git Bash, not Window's built in Command Prompt (`cmd`)
> get 'npm start' running on windows

- src/Controls/Geosearch.js
> display placeholder text immediately

- spec/Providers/FeatureLayerSpec.js
- src/Providers/FeatureLayer.js
resolves #146.
this change exposes the orderBy method of [`L.esri.query`](http://esri.github.io/esri-leaflet/api-reference/tasks/query.html#methods) to the provider as well.
``` js
var flProvider = L.esri.Geocoding.featureLayerProvider({
label: 'States',
url: 'http://sampleserver6.arcgisonline.com/arcgis/rest/services/Census/MapServer/3',
searchFields: ['STATE_NAME']
})
flProvider.orderBy('POP2007', 'ASC') // alaska has the smallest population, texas the largest (just the way they like it)
flProvider.suggestions('as', null, function (error, results) {
console.log(results);
});
```
previously we weren't plucking results from the top of the array returned by the service.  that needed fixed too.
@nickpeihl do you have time to give this a quick sanity check?  if so i'd be ready to merge and …
> add option to order results and make sure to pull from top

- src/Providers/FeatureLayer.js
> ensure old search strings are dropped

- package-lock.json
- src/Providers/GeocodeService.js
- src/Services/Geocode.js
> always fetch param name and append magic key if present

- src/Classes/GeosearchCore.js
- src/Controls/Geosearch.js
- src/Providers/FeatureLayer.js
- src/Providers/MapService.js
- src/Tasks/Geocode.js
- src/Tasks/ReverseGeocode.js
- src/Tasks/Suggest.js
Replaces importing all from Leaflet, which supports the new esm Leaflet
module (which has no default export) and makes tree-shaking the leaflet
library possible.
> Changes imports from Leaflet to be specific

- package-lock.json
- src/Controls/Geosearch.js
> dont use leaflet helper to wire up touchend

- package.json
> only build once during publish script

- package.json
- spec/Providers/ArcgisOnlineGeocoderSpec.js
- src/Providers/ArcgisOnlineGeocoder.js
- src/Tasks/Geocode.js
> make sure country filters are always passed through

- package-lock.json
- src/Controls/Geosearch.js
I am hoping that this resolves #213 and #214.  I tested on an Android device, and it appears that you are able to scroll through the suggestions and select one, as expected.
A live site with the contents of the `dist` folder from my PR is available at https://gis.ccpa.net/labs/leaflet-spa/county-sites/.
> Fixes Touch Device Suggestions Scrolling Issue

- debug/sample.html
- spec/Providers/ArcgisOnlineGeocoderSpec.js
- src/Providers/ArcgisOnlineGeocoder.js
- src/Tasks/Geocode.js
- src/Tasks/Suggest.js
> support "nearby" parameter

- CHANGELOG.md
- package-lock.json
- package.json
> update esri-leaflet version to ^3.0.0
